//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutPlanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkoutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkoutResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkoutPlanner.WorkoutResources", typeof(WorkoutResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn.
        /// </summary>
        internal static string Autumn {
            get {
                return ResourceManager.GetString("Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic instructions.
        /// </summary>
        internal static string BasicInstructions {
            get {
                return ResourceManager.GetString("BasicInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        internal static string BPM {
            get {
                return ResourceManager.GetString("BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breathing.
        /// </summary>
        internal static string Breathing {
            get {
                return ResourceManager.GetString("Breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calmdown.
        /// </summary>
        internal static string Calmdown {
            get {
                return ResourceManager.GetString("Calmdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Gong.
        /// </summary>
        internal static string ChiGong {
            get {
                return ResourceManager.GetString("ChiGong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossover {0}.
        /// </summary>
        internal static string Crossover {
            get {
                return ResourceManager.GetString("Crossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fittnes {0}.
        /// </summary>
        internal static string Fittnes {
            get {
                return ResourceManager.GetString("Fittnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form pairs and instructions.
        /// </summary>
        internal static string FormPairs {
            get {
                return ResourceManager.GetString("FormPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ki-box.
        /// </summary>
        internal static string KiBox {
            get {
                return ResourceManager.GetString("KiBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ki-Box {0} {1}.
        /// </summary>
        internal static string KiBoxTitle {
            get {
                return ResourceManager.GetString("KiBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility {0}.
        /// </summary>
        internal static string Mobility {
            get {
                return ResourceManager.GetString("Mobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaxation.
        /// </summary>
        internal static string Relaxation {
            get {
                return ResourceManager.GetString("Relaxation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song {0}.
        /// </summary>
        internal static string Song {
            get {
                return ResourceManager.GetString("Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        internal static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength {0}.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch pair.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmup.
        /// </summary>
        internal static string Warmup {
            get {
                return ResourceManager.GetString("Warmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout {0} {1}.
        /// </summary>
        internal static string WorkoutTitle {
            get {
                return ResourceManager.GetString("WorkoutTitle", resourceCulture);
            }
        }
    }
}
